[package]
name = "AptosLend"
version = "1.0.0"
authors = ["Your Name <your.email@example.com>"]

[addresses]
lending_protocol = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-stdlib"

[dev-addresses]
lending_protocol = "0xCAFE"

[dev-dependencies]
