[package]
name = "day03"
version = "1.0.0"
authors = []

[addresses]
day03 = "0x42"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }

[dev-addresses]

[dev-dependencies]
