[package]
name = "day04"
version = "1.0.0"
authors = []

[addresses]
day04 = "_"
day04_tasks = "_"
day04_answers = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
