[package]
name = "Day16_LiquidityPool"
version = "1.0.0"
authors = ["Aptos Course"]

[addresses]
day16 = "_"
deployer = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
