[package]
name = "Day12VotingSystem"
version = "1.0.0"
authors = []

[addresses]
voting_example = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
