[package]
name = "FlashLoan"
version = "1.0.0"
authors = ["Aptos Course"]

[addresses]
flash_loan = "_"
admin = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-addresses]
flash_loan = "0x42"
admin = "0x1234"
