[package]
name = "LendingProtocolArchitecture"
version = "1.0.0"
authors = ["Your Name"]

[addresses]
lending_addr = "_"
std = "0x1"
aptos_framework = "0x1"
aptos_std = "0x1"

[dev-addresses]
lending_addr = "0xCAFE"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
