[package]
name = "Day05_ModuleSystem"
version = "1.0.0"
edition = "2024.beta"

[addresses]
std = "0x1"
my_addr = "_"
lending = "_"
upgrade = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-stdlib"

[dev-addresses]
my_addr = "0x42"
lending = "0x43"
upgrade = "0x44"
