[package]
name = "Day15_AMM"
version = "1.0.0"
authors = ["Aptos Course"]

[addresses]
day15 = "_"
day15_exam = "_"
day15_practice = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
